---
- name: install sofwares on target machines
  hosts: all
  gather_facts: false
  become: true
  tasks:
          - name: install maven
            include_role: 
                name: "maven_install"
            
          - name: install tomcat
            include_role:
                name: "tomcat_install"        
