---
- name: install sofwares on target machines
  hosts: "{{ ENV }}"
  gather_facts: false
  become: true
  tasks:
          - name: install maven
            include_role: 
                name: "maven_install"
            
        
